### PR TITLE
Add custom Site(URL) Support

### PR DESCRIPTION
**Pull request by linarnan**
try add gitlab support.

### CODE REVIEW

**Comment by linarnan** [comment]
forget to note,  i was try use it in my Own site (gitlab)  but it didn't work.  and shows unknown provider. 
it's try to support `custom` site , not just gitlab support.

**Comment by linarnan** [comment]
related to #44

**Comment by vferko** [comment]
it tries to open `https://gitlab.example.com/frontend/frontend/blob/...`
which is wrong, correct is `https://gitlab.example.com/frontend/frontend/tree/...`

**Comment by ziyasal** [comment]
Hi @vferko thanks for that, fix pr is welcome :)

**Pull request merged**
