### PR TITLE
Fix integration with GH entreprise

### PR DESCRIPTION
**Pull request by testerez**
With the actual version I had "Unknown Git provider." no matter what I do.
And asking for the domain makes more sense IMO.

@gdziadkiewicz

### CODE REVIEW

**Comment by gdziadkiewicz** [comment]
@testerez 
I can't test your change right now on my instance of GH enterprise, but will be able to do that tomorrow. It would also be great to find out why it didn't work for you and if there are other cases in which it may not work properly.

**Comment by testerez** [comment]
The issue was that `github-url-from-git` needs to know the GHE domain otherwise it returns `undefined`.  
See: https://github.com/tj/node-github-url-from-git/blob/master/test.js#L69   
I wonder why it was working for you.

**Comment by gdziadkiewicz** [comment]
I just retested actual version and tested your fix. With current version for https I did not receive "Unknown Git provider.", but other problem appeared - the generated address was not valid( it contained ".git").  After your fix the generated address is valid. Current version with ssh behaves as you described(does not work). After your fix it works properly.  I am sorry for not testing my changes against ssh in the first place  and for not spotting the ".git"  problem. 

@ziyasal IMO it should be merged.

**Comment by testerez** [comment]
No worries. Thanks for your tests.

**Comment by ziyasal** [comment]
Hi @gdziadkiewicz, thank you for your tests; @testerez, thank you for your contribution

**Comment by ziyasal** [comment]
hi @all sorry for delay, new version published.

**Pull request merged**
